### ISSUE TITLE
assets compile error in production env

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/kokoro-io#211]
```
assets_1   | $ webpack --config ./webpack.config/prod.babel.js 
assets_1   | module.js:472
assets_1   |     throw err;
assets_1   |     ^
assets_1   | 
assets_1   | Error: Cannot find module '/usr/src/assets/webpack.config/prod.babel.js'
assets_1   |     at Function.Module._resolveFilename (module.js:470:15)
assets_1   |     at Function.Module._load (module.js:418:25)
assets_1   |     at Module.require (module.js:498:17)
assets_1   |     at require (internal/module.js:20:19)
assets_1   |     at requireConfig (/usr/src/assets/node_modules/webpack/bin/convert-argv.js:96:18)
assets_1   |     at /usr/src/assets/node_modules/webpack/bin/convert-argv.js:109:17
assets_1   |     at Array.forEach (native)
assets_1   |     at module.exports (/usr/src/assets/node_modules/webpack/bin/convert-argv.js:107:15)
assets_1   |     at Object.<anonymous> (/usr/src/assets/node_modules/webpack/bin/webpack.js:153:40)
assets_1   |     at Module._compile (module.js:571:32)
assets_1   | error Command failed with exit code 1.
assets_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
assets_1   | Done in 1.88s.
assets_1   | ERROR: "build:js" exited with 1.
assets_1   | error Command failed with exit code 1.
assets_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
assets_1   | ERROR: "build" exited with 1.
assets_1   | error Command failed with exit code 1.
```

**Comment by supermomonga** [comment]
https://github.com/supermomonga/kokoro-io/commit/c5a02f5871e1f2a3ee84e5c9d1cf1604f5c04304 fixed this.
